name: "Admin - Deploy Auto"

on:
  release:
    types: [published]

jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'admin'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_ADMIN}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs"
          procfile: "web: npm run start:prod"
        env:
          HD_PORT: 80
          HD_APP_VERSION: ${{ steps.extract_branch.outputs.branch }}
