name: "Admin - NodeJS Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'admin'
    - name: Set project dir environment var
      run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/admin"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, and test
      run: |
        npm ci
        npm run build
      env:
        CI: true
