name: Deploy

# on: 
#   push:
#     tags:
#     - '*'
on:
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs"
          procfile: "web: npm run start:prod"
        env:
          PORT: 80
